### ISSUE TITLE
Mythic Key Best tracking bugged in SL

### ISSUE THREAD

**Issue by resonatingDissonance** [SavedInstances/SavedInstances#463] opened 2021-01-26 17:16 UTC
**Describe the bug**
When logging into a character after opening WoW, the Mythic Key Best info is wiped out. Also, when switching characters from Character A to Character B, Character B's Mythic Key Best info is being overwritten with the Mythic Key Best info of Character A. This will keep happening to Characters C, D, etc. unless you open the game's Mythic Keystone panel, at which point that becomes the value that will incorrectly overwrite the Mythic Key Best info for future logins.

Lastly, after the weekly reset, only the first character you log into gets the Great Vault reward ready icon, but it doesn't go away after claiming the GV reward. It persists until you delete the character data.

**Do you have an error log of what happened?**
no

**To Reproduce**
1. Login into Character A
2. Logout, and login into Character B
3. Observe Character B's Mythic Key Best incorrectly displays Character A's Mythic Key Best

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
yes

**Which version of SavedInstances are you using?**
9.0.4

**Was it working in a previous version? If yes, which was the last good one?**
Was working in BFA.

**Additional context**

**Comment by LiangYuxuan** [comment] 2021-01-26 17:23
Please try alpha version which fixed this issue.

**Comment by keypulse** [comment] 2021-01-29 02:32
I was experiencing the same issue.  I downloaded alpha 9.0.4-1-gf0a6113 and while it didn't retro-fix the issue automatically, it worked after logging in each char that already ran a mythic this week and giving it a minute or so per char to update.  No side effects I can see.  Thanks!

**Comment by keypulse** [comment] 2021-01-29 03:51
> I was experiencing the same issue. I downloaded alpha 9.0.4-1-gf0a6113 and while it didn't retro-fix the issue automatically, it worked after logging in each char that already ran a mythic this week and giving it a minute or so per char to update. No side effects I can see. Thanks!

I take that back, after completing a new M+ it isn't showing on the character I just ran it on even after waiting several minutes and swapping characters and waiting several minutes again.  The new M+ entry isn't going in savedinstances.  Closing the game and going back in also did not show the recent M+ after installing alpha vers.

**Comment by LiangYuxuan** [comment] 2021-01-29 04:09
> > I was experiencing the same issue. I downloaded alpha 9.0.4-1-gf0a6113 and while it didn't retro-fix the issue automatically, it worked after logging in each char that already ran a mythic this week and giving it a minute or so per char to update. No side effects I can see. Thanks!
> 
> I take that back, after completing a new M+ it isn't showing on the character I just ran it on even after waiting several minutes and swapping characters and waiting several minutes again. The new M+ entry isn't going in savedinstances. Closing the game and going back in also did not show the recent M+ after installing alpha vers.

M+ record delay is a blizzard issue, would you like to check it in the Great Value and find out if it's tracked by blizzard?

**Comment by resonatingDissonance** [comment] 2021-01-31 00:53
Still seeing the last alt's Mythic Key Best info incorrectly overwriting the current character's info, but the permanent Great Vault Reward indicator seems to be fixed.

**Comment by keypulse** [comment] 2021-02-02 02:01
After each character viewed the great vault and a few days went by, everything is reporting as expected.  I believe viewing the great vault is the tie-in here.  In the meantime, I am using a macro for a remote view of the great vault to 'spark' the savedinstances data save:
/run LoadAddOn("Blizzard_WeeklyRewards");
/run if WeeklyRewardsFrame:IsShown() then WeeklyRewardsFrame:Hide() else WeeklyRewardsFrame:Show() end

Maybe this is required to use (silently) in the addon to populate the data correctly now?

**Comment by LiangYuxuan** [comment] 2021-02-02 02:22
It's weird that I can't reproduce this "overwriting" issue. I'll push a potential fix later today which is the macro actually do, `C_MythicPlus.RequestMapInfo()`.

**Closed** 2021-02-02 12:00 UTC
Labels: 🐛 Bug
