### ISSUE TITLE
Lua Error 9.1.5

### ISSUE THREAD

**Issue by keypulse** [SavedInstances/SavedInstances#549] opened 2021-11-03 04:39 UTC
I am getting the following LUA error while hovering over the minimap icon in 9.1.5, but it mentions UndermineJournal addon as well so I'm not quite sure where the issue resides:

`Message: ...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
Time: Wed Nov  3 00:36:31 2021
Count: 1
Stack: ...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:543: attempt to call method 'GetBackdrop' (a nil value)
[string "@Interface\AddOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:543: in function <...dOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:539>
[string "@Interface\AddOns\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua"]:132: in function `Acquire'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:3454: in function `ShowTooltip'
[string "@Interface\AddOns\SavedInstances\Core\Core.lua"]:2555: in function `OnEnter'
[string "@Interface\AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua"]:77: in function <...AddOns\DBM-Core\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>

Locals: tooltip = <unnamed> {
 0 = <userdata>
 scrollChild = <unnamed> {
 }
 scrollFrame = <unnamed> {
 }
}
key = "SavedInstancesTooltip"
(*temporary) = nil
(*temporary) = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 textLeft1Font = "GameTooltipHeaderText"
 ItemTooltip = <unnamed> {
 }
 SetCurrencyToken = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetGuildBankItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 updateTooltipTimer = 0.061000
 SetQuestRewardSpell = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 textRight2Font = "GameTooltipText"
 comparing = false
 TopOverlay = <unnamed> {
 }
 SetPetAction = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetLootItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetQuestItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 hasMoney = 1
 waitingForData = false
 SetTrainerService = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 numMoneyFrames = 1
 shoppingTooltips = <table> {
 }
 SetBagItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetInboxItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetBuybackItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 TextLeft1 = GameTooltipTextLeft1 {
 }
 SetHyperlink = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetMerchantItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetQuestLogItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetLootRollItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 BottomOverlay = <unnamed> {
 }
 SetTalent = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetTradePlayerItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 textRight1Font = "GameTooltipHeaderText"
 SetSendMailItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetInventoryItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 NineSlice = <unnamed> {
 }
 textLeft2Font = "GameTooltipText"
 SetShapeshift = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 TextRight2 = GameTooltipTextRight2 {
 }
 TextLeft2 = GameTooltipTextLeft2 {
 }
 SetTradeTargetItem = <function> defined @Interface\AddOns\TheUndermineJournal\libs\LibExtraTip\LibExtraTip.lua:419
 SetRecipeReagentItem = <functi`

**Comment by Duckwhale** [comment] 2021-11-03 05:38
Some info here: https://us.forums.blizzard.com/en/wow/t/backdroptemplate-issues/1125674/8

Haven't found anything official, so far...

**Comment by nilgid** [comment] 2021-11-03 11:44
Got the same issue, tryde to make some changes but did not work

**Comment by nilgid** [comment] 2021-11-03 12:50
made a quick fix that worked for me, untill it fixed by the author,
in file :\SavedInstances\Libs\LibQTip-1.0\LibQTip-1.0.lua:543

Background color is a bit off thoe, at least no Lua error


--	local backdrop = GameTooltip:GetBackdrop()

--	tooltip:SetBackdrop(backdrop)
	local GenericBackdrop = {
			bgFile = "Interface\\Tooltips\\UI-Tooltip-Background"
}
	tooltip:SetBackdrop(GenericBackdrop)

**Comment by gromchek** [comment] 2021-11-03 14:58
After `tooltip:SetBackdrop(GenericBackdrop)` add
```
tooltip:SetBackdropColor(0.06, 0.06, 0.06, 1.0)
tooltip:SetBackdropBorderColor(0.15, 0.15, 0.15, 1.0)
```
with your fav colors

**Comment by Stanzilla** [comment] 2021-11-03 15:16
The problem is in LibQTip-1.0 so we'll have to wait until someone updates it or switch to a fork

**Comment by Duckwhale** [comment] 2021-11-03 16:06
Some more details here: https://www.curseforge.com/wow/addons/libqtip-1-0/issues/49

**Comment by Quiksmage** [comment] 2021-11-03 17:17
following what others posted here worked for me.
Line 543 - comment out or remove
```
local backdrop = GameTooltip:GetBackdrop()

tooltip:SetBackdrop(backdrop
```

replace with
```
local GenericBackdrop = {
bgFile = "Interface\Tooltips\UI-Tooltip-Background"
}
tooltip:SetBackdrop(GenericBackdrop)
tooltip:SetBackdropColor(0.06, 0.06, 0.06, 1.0)
tooltip:SetBackdropBorderColor(0.15, 0.15, 0.15, 1.0)
```

Visual that may help others
![image](https://user-images.githubusercontent.com/12449533/140141712-67ab8f99-c3e9-4ecf-bee5-a7d5bfb00e8b.png)

**Comment by archxlock** [comment] 2021-11-03 19:11
As @Duckwhale referenced, I downloaded https://www.curseforge.com/wow/addons/libqtip-1-0 and it resolved the issue for me without having to edit the LUA file.

**Closed** 2021-11-03 19:36 UTC
