### ISSUE TITLE
8.0.1 PTR error message in UnitDebuff

### ISSUE THREAD

**Issue by yoshimo** [SavedInstances/SavedInstances#116] opened 2018-06-16 12:49 UTC
Running this addon on the current BFA ready PTR version results in:

> 
> ["message"] = "Interface\\AddOns\\SavedInstances\\SavedInstances.lua:1738: Usage: UnitDebuff(\"unit\", [index][, \"filter\"])",
> ["context"] = "Global",
> ["stack"] = "[C]: in function `UnitDebuff'\nInterface\\AddOns\\SavedInstances\\SavedInstances.lua:1738: in function `UpdateToonData'\nInterface\\AddOns\\SavedInstances\\SavedInstances.lua:2730: in function <Interface\\AddOns\\SavedInstances\\SavedInstances.lua:2730>\n(tail call): ?\n[C]: ?\n[string \"safecall Dispatcher[1]\"]:9: in function <[string \"safecall Dispatcher[1]\"]:5>\n(tail call): ?\n...nterface\\AddOns\\Ace3\\AceBucket-3.0\\AceBucket-3.0.lua:118: in function `func'\nInterface\\AddOns\\Ace3\\AceTimer-3.0\\AceTimer-3.0.lua:57: in function <Interface\\AddOns\\Ace3\\AceTimer-3.0\\AceTimer-3.0.lua:50>\n"

**Comment by SacredDuckwhale** [comment] 2018-07-18 09:41
I didn't have PTR access, nor time to investigate this. If it's an issue on live servers now, it will be fixed as soon as humanly possible :)

**Comment by Roddd** [comment] 2018-07-18 09:48
I get the same problem on live.
v7.0.13 (Release)

Message: Interface\AddOns\SavedInstances\SavedInstances.lua:1734: Usage: UnitDebuff("unit", [index][, "filter"])
Time: Wed Jul 18 02:45:28 2018
Count: 3
Stack: Interface\AddOns\SavedInstances\SavedInstances.lua:1734: Usage: UnitDebuff("unit", [index][, "filter"])
[C]: in function `UnitDebuff'
Interface\AddOns\SavedInstances\SavedInstances.lua:1734: in function `UpdateToonData'
Interface\AddOns\SavedInstances\SavedInstances.lua:2726: in function <Interface\AddOns\SavedInstances\SavedInstances.lua:2726>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...e\AddOns\Quartz\libs\AceBucket-3.0\AceBucket-3.0.lua:118: in function `func'
...Ons\Prat-3.0_Libraries\AceTimer-3.0\AceTimer-3.0.lua:55: in function <...Ons\Prat-3.0_Libraries\AceTimer-3.0\AceTimer-3.0.lua:48>

Locals: <none>

**Comment by SacredDuckwhale** [comment] 2018-07-18 10:43
I've identified the cause and am working on fixing it. Shouldn't be too complicated, really.

They changed the Aura functions when they removed the spell name from several functions in the process of streamlining their Spell System API. At least I hope that is all they did...

**Comment by SacredDuckwhale** [comment] 2018-07-18 11:58
It appears @Stanzilla has already been working on this as well. I'll leave it to him then to close the issue as resolved when it's done.

Note: I was opening the PR for submitting my work when I noticed it had already been fixed. Please use the assignment functionality of GitHub or post a quick note if you're working on an open issue to avoid this in the future. Thanks! :)

**Comment by Stanzilla** [comment] 2018-07-18 12:15
Sorry, I'm actually on vacation and just trying to get done what I can

**Closed** 2018-07-18 12:15 UTC
Labels: priority:urgent, status:in-progress, type:bug
