### ISSUE TITLE
lua error on mouseover

### ISSUE THREAD

**Issue by Ayshela** [SavedInstances/SavedInstances#273] opened 2019-04-23 19:14 UTC
updated to the new version on curseforge this morning, and the addon is completely unusable.  I mouseover the minimap icon and get an immediate lua error - this happens with every other addon disabled, as well as with my usual suspects running.

Message: Interface\AddOns\SavedInstances\SavedInstances.lua:775: attempt to concatenate field 'iconTexture' (a nil value)
Time: Tue Apr 23 14:06:27 2019
Count: 1
Stack: Interface\AddOns\SavedInstances\SavedInstances.lua:775: attempt to concatenate field 'iconTexture' (a nil value)
Interface\AddOns\SavedInstances\SavedInstances.lua:775: in function <Interface\AddOns\SavedInstances\SavedInstances.lua:766>
Interface\AddOns\SavedInstances\SavedInstances.lua:3825: in function `ShowTooltip'
Interface\AddOns\SavedInstances\SavedInstances.lua:2582: in function `OnEnter'
...ce\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:77: in function <...ce\AddOns\Atlas\Libs\LibDBIcon-1.0\LibDBIcon-1.0.lua:60>

Locals: current = <table> {
 monthDay = 23
 weekday = 3
 month = 4
 minute = 4
 hour = 12
 year = 2019
}
monthInfo = <table> {
 firstWeekday = 2
 numDays = 30
 year = 2019
 month = 4
}
month = 4
day = 23
year = 2019
showMonth = 4
showYear = 2019
monthOffset = 0
numEvents = 5
(for index) = 5
(for limit) = 5
(for step) = 1
i = 5
event = <table> {
 clubID = 0
 numSequenceDays = 8
 eventID = 666
 eventType = 4294967295
 sequenceType = "END"
 isCustomTitle = true
 startTime = <table> {
 }
 difficultyName = ""
 endTime = <table> {
 }
 invitedBy = ""
 dontDisplayEnd = true
 difficulty = 0
 inviteStatus = 1
 title = "PvP Brawl: Arathi Blizzard"
 calendarType = "HOLIDAY"
 inviteType = 1
 sequenceIndex = 8
 dontDisplayBanner = true
 modStatus = ""
}
(*temporary) = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:109
(*temporary) = "iconTexture: "
(*temporary) = nil
(*temporary) = 5
(*temporary) = "attempt to concatenate field 'iconTexture' (a nil value)"
debug = <function> defined @Interface\AddOns\SavedInstances\SavedInstances.lua:109
eventInfo = <table> {
 1467050 = true
 2576479 = true
 235476 = true
}

**Comment by LordDeimos666** [comment] 2019-04-24 00:37
Duplicate of #268 and #272

**Closed** 2019-04-24 03:15 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate
