### ISSUE TITLE
Unable to see "World" section of the Great Vault

### ISSUE THREAD

**Issue by userCentari11532** [SavedInstances/SavedInstances#884] opened 2024-09-17 20:34 UTC
I logged on to check my Great Vault for the week and was met with this: https://i.imgur.com/SxgEgZR.png
You are unable to select from what should be the "World" row of rewards. I and many in my guild had been having this issue last week but we chalked it up to a Blizzard bug since this row wasn't dynamic before The War Within, come to find after disabling addons for a minute that it seems to be Saved Instances. 

There are no errors thrown.

Reproduction is easy: Log on any of my 11 characters with Saved Instances turned on and it looks like it does in the above screenshot where I am unable to interact with the bottom row of rewards. When I turn off the addon and reload, the Great Vault looks normal again with rewards from Delves showing up.

Which version of SavedInstances are you using?
11.0.4

Different character, same thing:
Before turning SI off: https://i.imgur.com/V2ymUJp.png
After turning SI off: https://i.imgur.com/D9w2dmE.png

**Comment by LiangYuxuan** [comment] 2024-09-18 01:44
That's weird, SI don't touch any BLZ's UI.

**Comment by Stanzilla** [comment] 2024-09-18 06:37
it happens when you call Vault stuff via the API before opening the native UI. and even when opening the native UI, it takes ages for it to get all the data it needs. it's just broken.

**Comment by userCentari11532** [comment] 2024-09-18 15:34
Fair enough - I guess it was happenstance that it worked when I disabled Saved Instances. Admittedly, I don't know much about it but love the addon so if it was the issue, I wanted to get it looked at ASAP.

**Comment by LiangYuxuan** [comment] 2024-09-19 17:16
I can't reproduce this on two characters.

**Comment by immort4l** [comment] 2024-09-20 10:02
I spent some time troubleshooting this issue and can confirm it is not related to Savedinstances. After reading what Stanzilla said about early API call, i found that one of my weakauras did a custom on init load of the Vault's UI. Disabling that completely solved the problem. So it's an issue from some other addons/WAs, not from SI.

**Comment by LiangYuxuan** [comment] 2024-09-20 10:06
That's good to hear. Closing this, feel free to reopen if SI is found invoked.

**Closed by LiangYuxuan** 2024-09-20 10:06 UTC
Labels: 🐛 Bug, 🤷‍♀️ Can't Reproduce
