### ISSUE TITLE
bug with latest version 

### ISSUE THREAD

**Issue by Addonman** [SavedInstances/SavedInstances#269] opened 2019-04-22 20:10 UTC
Error occured in: Global
Count: 1
Message: ..\AddOns\SavedInstances\SavedInstances.lua line 775:
   attempt to concatenate field 'iconTexture' (a nil value)
Debug:
   ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:583:
      ...ce\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:543
   [C]: ?
   SavedInstances\SavedInstances.lua:775:
      SavedInstances\SavedInstances.lua:766
   SavedInstances\SavedInstances.lua:3825: ShowTooltip()
   SavedInstances\SavedInstances.lua:2582: OnEnter()
   Bazooka\Bazooka.lua:1582: showTip()
   Bazooka\Bazooka.lua:1387:
      Bazooka\Bazooka.lua:1378
Locals:
errMsg = "Interface\AddOns\SavedInstances\SavedInstances.lua:775: attempt to concatenate field 'iconTexture' (a nil value)"
tsmErrMsg = nil
oldModule = nil
private = <table> {
 AddonBlockedEvent = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:335
 num = 0
 ErrorHandler = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:116
 hitInternalError = false
 errorFrame = <unnamed> {
 }
 origErrorHandler = <function> defined @Interface\AddOns\Decursive\Dcr_DIAG.lua:585
 FormatErrorMessageSection = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:350
 SanitizeString = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:343
 errorReports = <table> {
 }
 IsTSMAddon = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:310
 localLinesTemp = <table> {
 }
 GetStackInfo = <function> defined @Interface\AddOns\TradeSkillMaster\Core\Lib\ErrorHandler.lua:278
}
MAX_STACK_DEPTH = 50
TSM = <table> {
}

**Comment by LordDeimos666** [comment] 2019-04-22 22:44
Duplicate of #268

**Closed** 2019-04-23 00:45 UTC
Labels: 🐛 Bug, 👯‍♀️ Duplicate
