### ISSUE TITLE
Lua Error when updating backdrop with ElvUI enabled

### ISSUE THREAD

**Issue by starcookies** [SavedInstances/SavedInstances#248] opened 2019-03-14 07:50 UTC
28x SavedInstances\SavedInstances-8.1.0.lua:3188: Usage: <unnamed>:SetBackdrop(nil or {bgFile = "bgFile", edgeFile = "edgeFile", tile = false, tileSize = 0, edgeSize = 32, insets = { left = 0, right = 0, top = 0, bottom = 0 }})
[C]: in function `SetBackdrop'
SavedInstances\SavedInstances-8.1.0.lua:3188: in function <SavedInstances\SavedInstances.lua:3184>

Locals:
(*temporary) = <unnamed> {
 0 = <userdata>
 regularFont = GameTooltipText {
 }
 OnRelease = <function> defined @SavedInstances\SavedInstances.lua:4336
 headerFont = SavedInstancedTooltipHeaderFont {
 }
 key = "SavedInstancesTooltip"
 scripts = <table> {
 }
 SetBackdropBorderColor = <function> defined =[C]:-1
 scrollFrame = <unnamed> {
 }
 anchorframe = LibDBIcon10_SavedInstances {
 }
 template = "Transparent"
 scrollChild = <unnamed> {
 }
 colspans = <table> {
 }
 width = 464.683899
 autoHideTimerFrame = <unnamed> {
 }
 labelProvider = <table> {
 }
 lines = <table> {
 }
 height = 374.447876
 SetBackdropColor = <function> defined =[C]:-1
 pixelBorders = <table> {
 }
 columns = <table> {
 }
}

**Comment by LiangYuxuan** [comment] 2019-03-14 13:31
Could you try to disable other addons and see if the issue is still there?

**Comment by mrdoom66** [comment] 2019-03-14 18:43
I have the same error. with all other addons disabled there is no error. First addon I have activated is the newest Version of ElvUI and then the error occurs.

**Comment by LiangYuxuan** [comment] 2019-03-15 04:18
I reproduce this after upgrading my ElvUI to 11.06. But is it a SavedInstances issue?

@starcookies @mrdoom66 Could you provide your ElvUI version when the first time you meet this issue?

**Comment by LiangYuxuan** [comment] 2019-03-15 04:54
I think I find a stable way to reproduce this. Open world map and hover on something opens tooltip, and then try to open SI's tooltip with `GameTooltip:GetBackdrop()` returning nil.

Simply comment this three lines out will work, but I think further investigation is required to solve this issue completely.

https://github.com/SavedInstances/SavedInstances/blob/6951e6661265a986e09ed5b146c5cd8eb5d6514a/SavedInstances/SavedInstances.lua#L3188-L3190

**Comment by mrdoom66** [comment] 2019-03-15 04:54
I think it started with ElvUI 11.05. Don´t know if it is a SavedInstances issue. 
For sure they changed something in ElvUI cos I used both addons for quite some time without any errors. But unfortunatly I have no knowledge of programming lua addons.
But I can report the error to the ElvUi team. Maybe they can fix something on their side.

**Comment by mrdoom66** [comment] 2019-03-15 04:56
OK, I will try this. TY

**Comment by Stanzilla** [comment] 2019-03-15 23:26
I think it's an AddonSkins issue?

**Comment by starcookies** [comment] 2019-03-18 19:29
> 06
I have elvui version 11.06 and shadow and light 3.521. it started happening with the recent update of elvui

**Comment by unleeshed** [comment] 2019-03-29 00:41
> I think it's an AddonSkins issue?

I spoke to them there. Definitely not their coding they say. Claims its a Saved Instances problem.

**Comment by LiangYuxuan** [comment] 2019-03-29 00:54
Hi, you can try latest alpha with temporarily fix for this. @unleeshed

**Comment by LiangYuxuan** [comment] 2019-03-29 01:15
I think this issue has two side. On the one hand, is it possible to drop this code? oscarucb comment that this code is to resolve QTip backdrop issue which was reported in ticket 155. But it is no longer possible to access WoWAce Ticket, which was considered to be closed in #63. I wonder if it is possible to access it by someone who is owner or author in the project, so we can find out why this code was added. @Stanzilla @jokeyrhyme 

On the other hand, it is only happening when ElvUI is enabled, which makes `GameTooltip:GetBackdrop()` returning nil. I tired to find out the reason in ElvUI's code but still have no idea about this.

**Comment by Stanzilla** [comment] 2019-03-29 03:07
Can be dropped for sure

**Closed** 2019-04-04 11:19 UTC
Labels: 🐛 Bug, 🙏 Help Wanted
