### ISSUE TITLE
Nil error on C_ChallengeMode.GetKeystoneLevelRarityColor won't return color on any key level

### ISSUE THREAD

**Issue by Toenail1203** [SavedInstances/SavedInstances#828] opened 2024-04-03 03:35 UTC
**Describe the bug**

lua error logging in and doing anything like buying from a vendor,  looting a corpse,  or moving an item in my bags. it just started today, been working fine up until now

**Do you have an error log of what happened?**

Message: ...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
Time: Tue Apr  2 22:22:06 2024
Count: 1
Stack: ...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:133: in function <...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:127>
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:146: in function `ProcessKey'
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:159: in function `RefreshMythicKeyInfo'
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:121: in function <...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/SavedInstances/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:66: in function <...ns/SavedInstances/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@Interface/AddOns/SavedInstances/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:523: in function `EnableAddon'
[string "@Interface/AddOns/SavedInstances/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:536: in function `EnableAddon'
[string "@Interface/AddOns/SavedInstances/Libs/AceAddon-3.0/AceAddon-3.0.lua"]:626: in function <...ns/SavedInstances/Libs/AceAddon-3.0/AceAddon-3.0.lua:611>
[string "=[C]"]: ?
[string "=[C]"]: in function `LoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:572: in function `UIParentLoadAddOn'
[string "@Interface/FrameXML/UIParent.lua"]:777: in function `MajorFactions_LoadUI'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:179: in function `SetUpMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:172: in function `RefreshMajorFactionList'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:167: in function `RefreshOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:158: in function <...sionLandingPage/Blizzard_DragonflightLandingPage.lua:154>
[string "=[C]"]: in function `CreateFrame'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_DragonflightLandingPage.lua"]:122: in function `CreateOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:63: in function `RefreshExpansionOverlay'
[string "@Interface/AddOns/Blizzard_ExpansionLandingPage/Blizzard_ExpansionLandingPage.lua"]:35: in function <...pansionLandingPage/Blizzard_ExpansionLandingPage.lua:33>

Locals: level = 19
color = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"
colorCache = <table> {
}
C_ChallengeMode_GetKeystoneLevelRarityColor = <function> defined =[C]:-1
Message: ...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
Time: Tue Apr  2 22:22:07 2024
Count: 1
Stack: ...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:133: attempt to index local 'color' (a nil value)
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:133: in function <...terface/AddOns/SavedInstances/Modules/MythicPlus.lua:127>
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:146: in function `ProcessKey'
[string "@Interface/AddOns/SavedInstances/Modules/MythicPlus.lua"]:159: in function `?'
[string "@Interface/AddOns/SavedInstances/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:109: in function <...ces/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Interface/AddOns/SavedInstances/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:19: in function <...ces/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Interface/AddOns/SavedInstances/Libs/CallbackHandler-1.0/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Interface/AddOns/SavedInstances/Libs/AceEvent-3.0/AceEvent-3.0.lua"]:120: in function <...ns/SavedInstances/Libs/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals: level = 19
color = nil
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'color' (a nil value)"
colorCache = <table> {
}
C_ChallengeMode_GetKeystoneLevelRarityColor = <function> defined =[C]:-1

 

**To Reproduce**
 

**Screenshots**

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

the above lua error is with all other addons disabled.

**Which version of SavedInstances are you using?**

most recent version 10.2.5

**Was it working in a previous version? If yes, which was the last good one?**

**Additional context**

i did get the errors with other addons installed, bagnon, details, and armory (all Ace-related i think). as i disabled one, another would be in the lua error.

excellent addon especially keeping track of several alts' activities.  first problem i have seen

edit: i turned on the addons that i have always used, but kept savedinstances off.  no errors so far.

**Comment by KyrosKrane** [comment] 2024-04-03 04:48
Quick and dirty fix just to silence the messages, until a real fix can be done: Change line 133 in SavedInstances > Modules > MythicPlus.lua to this:

```lua
    colorCache[level] = color and color:GenerateHexColor() or "ffffffff"
```

**Comment by KyrosKrane** [comment] 2024-04-03 05:09
This appears to be a Blizzard error. The root cause is that `C_ChallengeMode.GetKeystoneLevelRarityColor()` is returning `nil` for any integer value or any string value that can be coerced into an integer, and throws an error for any other value. The in game error message from testing the command indicates that the parameters haven't changed from what's documented on the wiki. That suggests the workaround I put into place above is the best short term solution, until Blizz fixes the issue. The alternative is to build out a color table and store it manually in the addon.

![image](https://github.com/SavedInstances/SavedInstances/assets/458727/af5e12a0-e4e9-4f8a-8cae-5410f913c13f)

**Comment by LiangYuxuan** [comment] 2024-04-03 07:43
Upstream issue: https://github.com/Stanzilla/WoWUIBugs/issues/544

Quick fix in #829 and consider coloring level the old way if blz won't fix after Dragonflight Season 4 starts.

**Comment by KyrosKrane** [comment] 2024-04-03 22:51
I don't recommend this since the workaround is good enough for now, but if you do decide to build out a color table and temporary replacements for the broken Blizz functions, Numynum has a good implementation here, that can easily be adapted.
https://github.com/NumyAddon/MythicPlusTweaks/commit/835e006f718daf3bcccf1b657530876a690fb9ef

**Comment by KyrosKrane** [comment] 2024-04-10 00:56
As of today's patch, `C_ChallengeMode.GetKeystoneLevelRarityColor()` is again returning data instead of nil.

**Comment by LiangYuxuan** [comment] 2024-04-10 01:34
So we can close it for now.

**Closed by LiangYuxuan** 2024-04-10 01:34 UTC
Labels: 🐛 Bug, ⬆️ Upstream Issue
