### ISSUE TITLE
Duplicate tabs

### ISSUE THREAD

**Issue by gaveer** [SavedInstances/SavedInstances#599] opened 2022-07-24 09:25 UTC
**Describe the bug**

- @Stanzilla  The Taps for Shadowland show duplicated **LFR**

**Do you have an error log of what happened?**
 
No

**To Reproduce**
 

**Screenshots**
![Screenshot_10](https://user-images.githubusercontent.com/45834601/180640634-2d5654e1-f751-459c-bb71-061de056ae9e.png)

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**
- i did not try that 
**Which version of SavedInstances are you using?**
- [9.2.2]
**Was it working in a previous version? If yes, which was the last good one?**
- i can recall that 
**Additional context**

**Comment by LiangYuxuan** [comment] 2022-07-24 10:41
This is caused by #578 which is workaround for #547 . Instances that without LFR prefix are found by generic instances scan, and the others are defined in LFR module. If related issue is not fixed in DF, I think dropping LFR module is a accpectable way to fix this.

**Comment by gaveer** [comment] 2022-07-24 12:30
want me to close the ticket ?

**Closed** 2024-01-11 06:52 UTC
Labels: 🐛 Bug
